# Define your constants here

ENDPOINT_QUERY_REPUTATION_V3 = "/Talos.Service.URS/QueryReputationV3"
ENDPOINT_QUERY_AUP_CAT_MAP = "/Talos.Service.URS/QueryAUPCatMap"
ENDPOINT_QUERY_TAXONOMIES = "/Talos.Service.TTS/QueryTaxonomyCatalogs"
ENDPOINT_ENRICH_DOMAIN = "/Talos.Service.ENRICH/QueryDomain"
ENDPOINT_ENRICH_URL = "/Talos.Service.ENRICH/QueryURL"
ENDPOINT_ENRICH_IP = "/Talos.Service.ENRICH/QueryIP"
ENDPOINT_ENRICH_DOMAIN_STIX = "/Talos.Service.ENRICH/QueryDomainSTIX"
ENDPOINT_ENRICH_URL_STIX = "/Talos.Service.ENRICH/QueryURLSTIX"
ENDPOINT_ENRICH_IP_STIX = "/Talos.Service.ENRICH/QueryIPSTIX"
ENDPOINT_DOMAIN_PREVALENCE = "/Talos.Service.ENRICH/QueryDomainPrevalence"
MAX_CONNECTION_RETIRIES = 10
MAX_REQUEST_RETRIES = 2
MITRE_ATTACK_TAX_ID = 7
